# [Info]
site_name: Blog
site_url: https://YMnRb.GitHub.io/blog
site_author: YMnRb
site_description: YMnRb's Blogs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: blue
      toggle:
        icon: octicons/sun-16 
        name: Switch to dark mode 切换至夜晚模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode 切换至明亮主题
  icon:
    logo: material/book
    admonition:  # for admonitions
      # note: fontawesome/solid/note-sticky
      # abstract: fontawesome/solid/book
      # info: fontawesome/solid/circle-info
      # tip: fontawesome/solid/bullhorn
      # success: fontawesome/solid/check
      # question: fontawesome/solid/circle-question
      # warning: fontawesome/solid/triangle-exclamation
      # failure: fontawesome/solid/bomb
      # danger: fontawesome/solid/skull
      # bug: fontawesome/solid/robot
      # example: fontawesome/solid/flask
      # quote: fontawesome/solid/quote-left
      hint: octicons/light-bulb-16
      提示: octicons/light-bulb-16
      warning: material/fire
      警告: material/fire
  font:
    text: Oppo Sans
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.path # exclusive Insiders features for sponsors only
    - navigation.indexes
    - toc.follow
    - content.tabs.link

extra:
  social:
    - icon: octicons/mail-16
      link: mailto:ymnrb@ymnrbms.onmicrosoft.com
      name: Mail me to ymnrb@ymnrbms.onmicrosoft.com; however I don't check my mailbox often. 

markdown_extensions:
  - admonition # for admonitions
  - pymdownx.details # for admonitions
  - pymdownx.superfences # for admonitions
  - pymdownx.arithmatex:
      generic: true # for KaTeX
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - .config/javascripts/katex.js # for KaTeX
  - .config/unpkg-katex@0.16.11/katex.min.js # https://unpkg.com/katex@0/dist/katex.min.js # for KaTeX
  - .config/unpkg-katex@0.16.11/contrib/auto-render.min.js # https://unpkg.com/katex@0/dist/contrib/auto-render.min.js # for KaTeX
extra_css:
  - .config/unpkg-katex@0.16.11/katex.min.custom.css # https://unpkg.com/katex@0/dist/katex.min.css # for KaTeX
  - .config/stylesheets/extra.css # for fonts

# [Navigation]
nav:
  - Index: index.md
  - Blog: 
    - lighthouse.md

# [Plugin]
plugins:
  - blog